// Shared styles for the bell's tab panels (feed / activity / alerts). Split out of
// Notifications.tsx (W27-4) so each panel file styles itself the same way.

export const PS: Record<string, React.CSSProperties> = {
  body: { maxHeight: 420, overflowY: "auto", padding: "6px 0" },
  barRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "4px 14px 8px",
  },
  dim: { color: "var(--text-faint)", fontSize: "var(--fs-xs)" },
  linkBtn: {
    background: "transparent",
    color: "var(--accent-quiet)",
    border: "none",
    fontSize: "var(--fs-xs)",
    cursor: "pointer",
  },
  empty: { color: "var(--text-faint)", fontSize: "var(--fs-sm)", padding: "12px 14px" },
  search: { width: "calc(100% - 28px)", margin: "0 14px 8px", height: 28, fontSize: "var(--fs-sm)" },
  note: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "9px 14px",
    borderTop: "1px solid var(--border-hairline)",
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: "var(--r-pill)",
    background: "var(--accent)",
    marginTop: 5,
    flexShrink: 0,
  },
  noteMsg: { fontSize: "var(--fs-sm)", color: "var(--text)" },
  noteTime: { fontSize: "var(--fs-2xs)", color: "var(--text-faint)", marginTop: 2 },
  daySep: { fontSize: "var(--fs-2xs)", textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--text-faint)", padding: "8px 14px 2px" },
  form: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 14px",
    flexWrap: "wrap",
  },
  repeat: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: "var(--fs-xs)",
    color: "var(--text-muted)",
    cursor: "pointer",
  },
  formMsg: { fontSize: "var(--fs-xs)", color: "var(--warn)", padding: "0 14px 6px" },
  tagRepeat: {
    fontSize: 10,
    color: "var(--accent-quiet)",
    border: "1px solid #3a4a5a",
    borderRadius: "var(--r-sm)",
    padding: "0 5px",
    marginLeft: 6,
    textTransform: "uppercase",
  },
  tagDone: {
    fontSize: 10,
    color: "var(--warn)",
    border: "1px solid var(--warn-border)",
    borderRadius: "var(--r-sm)",
    padding: "0 5px",
    marginLeft: 6,
    textTransform: "uppercase",
  },
};
