"""audit_event fill_key unique idempotency

Revision ID: 3e5f7fce03c5
Revises: fb9a13a6acb6
Create Date: 2026-06-30 15:22:33.544963
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5f7fce03c5'
down_revision: Union[str, Sequence[str], None] = 'fb9a13a6acb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_event', sa.Column('fill_key', sa.String(length=160), nullable=True))
    op.create_unique_constraint(None, 'audit_event', ['fill_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_event', type_='unique')
    op.drop_column('audit_event', 'fill_key')
    # ### end Alembic commands ###
