"""baseline schema

Revision ID: d26076653728
Revises: 
Create Date: 2026-06-30 01:06:48.465583
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26076653728'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_config',
    sa.Column('account_hash', sa.String(length=64), nullable=False),
    sa.Column('trading_enabled', sa.Boolean(), nullable=False),
    sa.Column('strategy_json', sa.String(), nullable=True),
    sa.Column('tax_filing', sa.String(length=16), nullable=False),
    sa.Column('tax_state_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('account_hash')
    )
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('completed_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_hash', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('shares', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('cost', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('profit', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=False),
    sa.Column('schwab_order_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completed_trade_account_hash'), 'completed_trade', ['account_hash'], unique=False)
    op.create_index(op.f('ix_completed_trade_symbol'), 'completed_trade', ['symbol'], unique=False)
    op.create_table('daily_balance',
    sa.Column('account_hash', sa.String(length=64), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('capital_gains', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('gross_sales', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('account_hash', 'day')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_alert_id'), 'notification', ['alert_id'], unique=False)
    op.create_index(op.f('ix_notification_symbol'), 'notification', ['symbol'], unique=False)
    op.create_table('price_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('repeat', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alert_symbol'), 'price_alert', ['symbol'], unique=False)
    op.create_table('ticker',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('watch', sa.Boolean(), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('day_high', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('day_low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('year_high', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('year_low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('quote_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_hash', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('rung', sa.Integer(), nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('sell_mode', sa.String(length=16), nullable=True),
    sa.Column('sell_target_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('schwab_order_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['ticker.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_account_hash'), 'lot', ['account_hash'], unique=False)
    op.create_index(op.f('ix_lot_symbol'), 'lot', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_symbol'), table_name='lot')
    op.drop_index(op.f('ix_lot_account_hash'), table_name='lot')
    op.drop_table('lot')
    op.drop_table('ticker')
    op.drop_index(op.f('ix_price_alert_symbol'), table_name='price_alert')
    op.drop_table('price_alert')
    op.drop_index(op.f('ix_notification_symbol'), table_name='notification')
    op.drop_index(op.f('ix_notification_alert_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_table('daily_balance')
    op.drop_index(op.f('ix_completed_trade_symbol'), table_name='completed_trade')
    op.drop_index(op.f('ix_completed_trade_account_hash'), table_name='completed_trade')
    op.drop_table('completed_trade')
    op.drop_table('app_setting')
    op.drop_table('account_config')
    # ### end Alembic commands ###
