"""lot source column

Revision ID: dc4f392e7cd0
Revises: 3e5f7fce03c5
Create Date: 2026-06-30 20:20:50.884037
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4f392e7cd0'
down_revision: Union[str, Sequence[str], None] = '3e5f7fce03c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('source', sa.String(length=12), server_default='fill', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lot', 'source')
    # ### end Alembic commands ###
