"""add audit_event table

Revision ID: fb9a13a6acb6
Revises: d300ebe5da67
Create Date: 2026-06-30 15:10:49.042052
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9a13a6acb6'
down_revision: Union[str, Sequence[str], None] = 'd300ebe5da67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_hash', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('shares', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('order_type', sa.String(length=16), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_account_hash'), 'audit_event', ['account_hash'], unique=False)
    op.create_index(op.f('ix_audit_event_symbol'), 'audit_event', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_event_symbol'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_account_hash'), table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
